github = "https://github.com/oknozor/musicbrainz_rs"

authors = [
    { signature = "Paul Delafosse", username = "oknozor" },
    { signature = "okno", username = "oknozor" },
    { signature = "Ritiek Malhotra", username = "ritiek" },
]


changelog_path = "CHANGELOG.md"

pre_bump_hooks = [
    "sh -c \"./ci/check_branch.sh\"",
    "cargo test -- --test-threads 1",
    "cargo clippy",
    "cargo build --release",
    "cargo fmt --all",
    "cargo bump {{version}}",
]


post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
    "cargo package",
    "cargo publish"
]
